In [89]:
import numpy as np

In [ ]:
# 1. Create an array from 1 to 10

array_1 = np.array([1,2,3,4,5,6,7,8,9,10])



In [ ]:
# 2. Print the array

print(array_1)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# 3. Find max and min

print("max:",np.max(array_1))
print("min:",np.min(array_1))


max: 10
min: 1


In [ ]:
# 4. Array of zeros

zeros = np.zeros(5)
print(zeros)

[0. 0. 0. 0. 0.]


In [ ]:
# 5. Array of ones

ones=np.ones(5)
print(ones)

[1. 1. 1. 1. 1.]


In [ ]:
# 6. Create a matrix

matrix_1 =np.array([[1,2,3],[4,5,6]])

In [ ]:
# 7. Display the matrix

print(matrix_1)

[[1 2 3]
 [4 5 6]]


In [ ]:
 # 8
 # . Show dimensions using .shape
 
print("dimensions(shape):",matrix_2.shape)

dimensions(shape): (2, 3)
