In [3]:
import numpy as np

In [7]:
# 1. Create an array from 1 to 10

array_1 = np.array([1,2,3,4,5,6,7,8,9,10])



In [8]:
# 2. Print the array

print(array_1)

[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
# 3. Find max and min

print("max:",np.max(array_1))
print("min:",np.min(array_1))


max: 10
min: 1


In [10]:
# 4. Array of zeros

zeros = np.zeros(5)
print(zeros)

[0. 0. 0. 0. 0.]


In [11]:
# 5. Array of ones

ones=np.ones(5)
print(ones)

[1. 1. 1. 1. 1.]


In [12]:
# 6. Create a matrix

matrix_1 =np.array([[1,2,3],[4,5,6]])

In [13]:
# 7. Display the matrix

print(matrix_1)

[[1 2 3]
 [4 5 6]]


In [14]:
 # 8. Show dimensions using .shape
 
print("dimensions(shape):",matrix_1.shape)

dimensions(shape): (2, 3)
